imgedit/edit/urls.py
#from django.urls.static import static
#from django.conf import settings
from django.urls import path, include
from . import views

app_name = 'edit'

urlpatterns = [
    path('', views.first_page, name='first_page'),
    path('show_all/', views.show_all, name='show_all'),
    path('upload/', views.upload, name='upload'),
    path('edit/<int:shomare>/', views.edit, name='edit')
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imgedit/imgedit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edit.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imgedit/edit/models.py
from django.db import models

# Create your models here.
class aks(models.Model):
    img = models.ImageField(default='', blank=True)
    show = models.BooleanField(default=False)

imgedit/edit/forms.py
from django import forms
from . import models

class get_image(forms.ModelForm):
    class Meta:
        model = models.aks
        fields = ['img', 'id']

imgedit/edit/views.py
from django.shortcuts import render, redirect
from .models import aks
from . import forms
from django.http import HttpResponse
from PIL import Image
import os
# Create your views here.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def show_all(request):
    all_img = aks.objects.all()
    return render(request, 'edit/show_all.html', {'all_img':all_img})

def first_page(request):
    if(request.method == 'POST'):
        if(request.POST['first_action'] == 'show'):
            return redirect('edit:show_all')
        else:
            return redirect('edit:upload')
    else:
        return render(request, 'edit/first_page.html')

def upload(request):
    if(request.method == 'POST'):
        form = forms.get_image(request.POST, request.FILES)
        if(form.is_valid()):
            a = form.save()
            #return redirect('/edit/' + str(aks.objects.latest('id').id) + '/')
            return redirect('/edit/' + str(a.id) + '/')
        else:
            form = forms.get_image()
            return render(request, 'edit/failed_upload.html', {'get_image': form})
    else:
        form = forms.get_image()
        return render(request, 'edit/upload.html', {"get_image":form})

def edit(request, shomare):
    if(request.method == 'POST'):
        if(request.POST.get('go_back', '') == 'go back to first page'):
            return redirect('edit:first_page')

        edit_type = request.POST['edit_type']
        last_img = aks.objects.get(id=shomare)
        cur = Image.open(last_img.img.path)

        if(edit_type == 'crop'):
            crop_left = int(request.POST['crop_left'])
            crop_up = int(request.POST['crop_up'])
            crop_right = int(request.POST['crop_right'])
            crop_down = int(request.POST['crop_down'])
            if(crop_down > last_img.img.height or crop_right > last_img.img.width or crop_up >= crop_down or crop_left >= crop_right):
               return redirect('/edit/' + str(shomare) + '/')
            cur.crop((crop_left, crop_up, crop_right, crop_down)).save(last_img.img.path)

        if(edit_type == 'resize'):
            resize_width = int(request.POST['resize_width'])
            resize_height = int(request.POST['resize_height'])
            cur.resize((resize_width, resize_height)).save(last_img.img.path)

        if(edit_type == 'convert'):
            cur.convert(mode='L').save(last_img.img.path)

        if(edit_type == 'rotate'):
            cur.rotate(int(request.POST['rotation_degree'])).save(last_img.img.path)

        if(edit_type == 'share'):
            last_img.show = True
            last_img.save()
            return redirect('edit:show_all')

        return redirect('/edit/' + str(shomare) + '/')
    else:
        last_img = aks.objects.get(id=shomare)
        return render(request, 'edit/edit.html', {'last_img':last_img})

imgedit/edit/templates/edit/edit.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>current pic</h1>
    <img src="{{last_img.img.url}}">
    <form action="{% url 'edit:edit' shomare=last_img.id %}" method="post">
      {% csrf_token %}
      <p>for croping the pictue insert left top right down</p>
      <input type="number" name="crop_left" value=0>
      <input type="number" name="crop_up" value=0>
      <input type="number" name="crop_right" value=1>
      <input type="number" name="crop_down" value=1>

      <p>for resizing the picture insert width height</p>
      <input type="number" name="resize_width" value=1>
      <input type="number" name="resize_height" value=1>

      <p>for rotating insert the degree</p>
      <input type="number" name="rotation_degree" value=0>

      <p>choose what kind of change you wanna make</p>
      <input required type="radio" name="edit_type" value="crop">crop<br>
      <input required type="radio" name="edit_type" value="resize">resize<br>
      <input required type="radio" name="edit_type" value="convert">convert<br>
      <input required type="radio" name="edit_type" value="rotate">rotate<br>
      <input required type="radio" name="edit_type" value="share">share<br>

      <input type="submit" value="apply">
      <input type="submit" name="go_back" value="go back to first page">
    </form>
  </body>
</html>

imgedit/edit/templates/edit/failed_upload.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>FAILED TO UPLOAD CORRECTLY</h1>
    <form action="{% url 'edit:upload' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{get_image}}
      <input type="submit" value="upload">
    </form>
  </body>
</html>

imgedit/edit/templates/edit/first_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action="{% url 'edit:first_page' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="first_action" value="upload">
      <input type="submit" name="first_action" value="show">
    </form>
  </body>
</html>

imgedit/edit/templates/edit/show_all.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% for single_img in all_img %}
      {% if single_img.show %}
        <img src="{{single_img.img.url}}">
      {% endif %}
    {% endfor %}
    <form action="{% url 'edit:first_page' %}" method="get">
      {% csrf_token %}
      <input type="submit" value="go back to first page">
    </form>
  </body>
</html>

imgedit/edit/templates/edit/upload.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action="{% url 'edit:upload' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{get_image}}
      <input type="submit" value="upload">
    </form>
  </body>
</html>